api_key: "01766580-322b-48aa-997a-9bc4462e471d"
iri: "http://imise.uni-leipzig.de/annotation.owl#"
outputPath: "annotation.owl"
ontologies: "MESH,SNOMEDCT,NCIT"
bioportal_url: "http://data.bioontology.org"